### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by Cysioland** [TheCactusVert/mpv-sponsorblock#13]
Could the config be documented better? Eg. what is the "poi" or "full" action in `action_types`?

**Comment by eternaleye** [comment]
Another aspect of missing documentation - how can a user have different actions for different segments, e.g. `skip` for `sponsor` and `music_offtopic`, but `mute` for `intro` and `outro`? I'd have expected the config to make use of TOML features for this, looking more like:

```TOML
# Server address
server_address = "https://sponsor.ajay.app"
# Get segments for a video with extra privacy 
privacy_api = false
# Third party YouTube domains like Piped, Invidious or CloudTube
domains = ["piped.kavin.rocks", "invidious.kavin.rocks"]
# Use OSD when a segment is skipped or muted
skip_notice = false

[[segment]]
# Categories: sponsor, selfpromo, interaction, poi_highlight, intro, outro, preview, music_offtopic, filler, exclusive_access
categories = ["sponsor", "music_offtopic"]
# Action types: skip, mute, poi, full
action = ["skip"]

[[segment]]
categories = ["intro", "outro"]
action = ["mute"]
```
but I can't tell if this is inexpressible, or merely configured in a less-than-obvious way.

**Comment by TheCactusVert** [comment]
I can't totally control the sponsorblock API.

Take this video for example: https://www.youtube.com/watch?v=ypynV-o5ox8

I can make a `curl` request to the SponsorBlock API. I want to mute the sponsor segments and to skip the outro because why not.

```toml
[[segment]]
categories = ["sponsor"]
action = ["mute"]

[[segment]]
categories = ["outro"]
action = ["skip"]
```

But I can't say to the API that I don't want the `skip` action for the `sponsor` segment, so the command will end up like this anyway:

```bash
❯ curl "https://sponsor.ajay.app/api/skipSegments?videoID=ypynV-o5ox8&category=sponsor&category=outro&actionType=skip&actionType=mute"
[{"category":"sponsor","actionType":"mute","segment":[0,2.815198],"UUID":"331df68b34e1668e9b8fd7a804e2e87cf0ba05e466b583109ab04854096e7821e","videoDuration":209.661,"locked":1,"votes":14,"description":""},{"category":"outro","actionType":"skip","segment":[175.028,178.919],"UUID":"9befb8fc2f928377782898fa51807d1466ca40e129a4b3cf8d58932f1064dc5b6","videoDuration":210,"locked":0,"votes":1,"description":""},{"category":"sponsor","actionType":"skip","segment":[178.88664,205.7519],"UUID":"85ecdc53ee50eea291014f0d48e0a88414099682a587c03f95ddeb48e9cd709d","videoDuration":210,"locked":1,"votes":14,"description":""}]%
```

I like your idea so maybe I could filter the segments based on the configuration. I didn't want to make the system more complex than it should be and wanted to rely solely on the API, maybe it was a mistake.
