### ISSUE TITLE
Sponsorblock works and skips the sections but only audio plays! Video doesn't play!

### ISSUE THREAD

**Issue by lamyergeier** [TheCactusVert/mpv-sponsorblock#5]
Note: Without this extension mpv plays youtube video without any trouble!

---

- Configuration

```toml
$ cat sponsorblock.toml

# Server address
server_address = "https://sponsor.ajay.app"
# Categories: sponsor, selfpromo, interaction, poi_highlight, intro, outro, preview, music_offtopic, filler, exclusive_access
categories = ["sponsor", "selfpromo", "interaction", "poi_highlight", "intro", "outro", "preview", "music_offtopic", "exclusive_access"]
# Action types: skip, mute, poi, full
action_types = ["skip"]
# Get segments for a video with extra privacy 
privacy_api = false
# Third party YouTube domains like Piped, Invidious or CloudTube
domains = ["piped.kavin.rocks", "invidious.kavin.rocks"]
# Use OSD when a segment is skipped or muted
skip_notice = false
```

- Example (with extension)

```
$ mpv https://www.youtube.com/watch?v=6YF0XNMpyoM
 (+) Video --vid=1 (*) (vp9 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
File tags:
 Uploader: Jonathan Antoine
 Channel_URL: https://www.youtube.com/channel/UC1aQpzmR_Nf0C7ElGiySLQg
[vo/gpu/wayland] GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback.
AO: [pipewire] 48000Hz stereo 2ch floatp
AV: 00:00:31 / 00:05:37 (9%) A-V:  0.000 Cache: 305s/12MB
```

---

- Example (without extension)

```
$ mpv https://www.youtube.com/watch?v=6YF0XNMpyoM
 (+) Video --vid=1 (*) (vp9 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
File tags:
 Uploader: Jonathan Antoine
 Channel_URL: https://www.youtube.com/channel/UC1aQpzmR_Nf0C7ElGiySLQg
[vo/gpu/wayland] GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback.
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:03 / 00:05:37 (1%) A-V:  0.000 Cache: 63s/28MB
```
